if: branch = master
language: node_js
node_js: lts/*
cache: yarn
jobs:
  include:
    - stage: test
      before_install: nvm use 10.15.3
      install: yarn install
      script:
        - yarn build
        - yarn test:ci
    - stage: deploy
      script: true
