language: node_js
node_js: lts/*
jobs:
  include:
    - stage: test
      before_install: nvm use 10.15.3
      install: true
      script: node --version
    - stage: deploy
      install: true
      script: true
      deploy: node --version
